### PR TITLE
Multifile upload

### LINKED ISSUE #3: Multiple files vs single files

### PR DESCRIPTION
**Pull request by jankapunkt**
Attempt to fix #3 with a real multiple file select that automatically adds all selected files to an Autoform Array list. Updated README documentation about that part, too. Backwards compatible and also allows single files within multiple files, too.

@dr-dimitru if this okay so far, would you bump the version and release, please?

### CODE REVIEW

**Comment by jankapunkt** [comment]
This is closed and will be reopened , once #53 is merged, because #53 respects to pass these config flags (backward compatible) to custom templates while this PR does not. Chages should be done accordingly to pass `multiple` as config flag via `uploadTemplateData`:

```javascript
  uploadTemplateData() {
    const instance = Template.instance();
    const currentUpload = instance.currentUpload.get();
    const { accept } = instance;
    const { multiple } = instance;

    // here we can check for upload template configs, that have been added after 2.1.4 and return either
    // an object with "config" merged with "currentUpload" to stay backwards compatible as popssible
    if (accept || multiple) {
      const config = { config: { accept, multiple } };
      return Object.assign({}, config, currentUpload);
    } else {
      return currentUpload;
    }
  },
```

**Comment by roblingle** [comment]
@jankapunkt Can this be re-opened and merged now?

**Comment by jankapunkt** [comment]
Hi @roblingle yes and no, I closed it, since it contained partial code from the pr #52 and I did not wanted to mess up the code base. However, I should open a new WIP branch, where the multifile code is integrated. I got it working once, so it should not be that hard to do it again. Thank you for your interest in this PR.

**Comment by jankapunkt** [comment]
@roblingle there is a new PR: https://github.com/VeliovGroup/meteor-autoform-file/pull/58 and the branch is `multiple2`. You can clone and switch to the multiple2 branch and check if this is sufficient for your use case. Feel free to comment the PR about any issue with the feature. A short review would be great.

**Pull request closed without merging**
