### PR TITLE
Update to aldeed:autoform@6.0.0 and simpl-schema npm package

### PR DESCRIPTION
**Pull request by Buom01**
Hi,
this is a quick update:
- If I don't make mistake, `SimpleSchema.messages` don't seem to work anymore
- So, SimpleSchema is not called from the package anymore. The error messages must be configured manually.

### CODE REVIEW

**Comment by dr-dimitru** [comment]
Hi @Buom01 ,

Thank you for PR, significant breaking changes here.

 1. Have you tested it in real app?
 2. I'm running all tests on [this demo app](https://github.com/VeliovGroup/files-gridfs-autoform-example) could you test your changes with it?
 3. I've been trying to use with `aldeed:autoform@6.0.0` [this demo app](https://github.com/VeliovGroup/files-gridfs-autoform-example) but it doesn't let me even use `v6.0.0` due to incompatibility

**Comment by dr-dimitru** [comment]
@Buom01 any news on your end? Could you respond to my comments, please

**Comment by Buom01** [comment]
Sorry i'm quite busy

1. Only in development on my app, I haven't tried to build it. 
2. and 3. I had looking to it, but I haven't solved any problems after any time.
I will look at it when I have time

**Comment by dr-dimitru** [comment]
Hello @Buom01 ,

Thank you for response, I'm not able to merge due to errors described in [PR review](https://github.com/VeliovGroup/meteor-autoform-file/pull/21#discussion_r106321587). Could you take a look on it?

**Comment by marcoschwartz** [comment]
Any news about this? So far autoform 6.0 is unusable with files

**Pull request merged**
